//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace LibraryManagement
{
    partial class LoginRegisterForm
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.txtLoginPassword = new System.Windows.Forms.TextBox();
            this.lblLoginPassword = new System.Windows.Forms.Label();
            this.pnlSidebar = new System.Windows.Forms.Panel();
            this.iconBook = new FontAwesome.Sharp.IconPictureBox();
            this.lblAppName = new System.Windows.Forms.Label();
            this.lblAppSubtitle = new System.Windows.Forms.Label();
            this.pnlRight = new System.Windows.Forms.Panel();
            this.pnlLogin = new System.Windows.Forms.Panel();
            this.lblLoginTitle = new System.Windows.Forms.Label();
            this.lblLoginSubtitle = new System.Windows.Forms.Label();
            this.lblLoginEmail = new System.Windows.Forms.Label();
            this.txtLoginEmail = new System.Windows.Forms.TextBox();
            this.lblLoginEmailError = new System.Windows.Forms.Label();
            this.btnShowLoginPassword = new FontAwesome.Sharp.IconButton();
            this.lblLoginError = new System.Windows.Forms.Label();
            this.btnLogin = new System.Windows.Forms.Button();
            this.btnGoToRegister = new FontAwesome.Sharp.IconButton();
            this.pnlRegister = new System.Windows.Forms.Panel();
            this.lblRegTitle = new System.Windows.Forms.Label();
            this.lblRegSubtitle = new System.Windows.Forms.Label();
            this.lblRegName = new System.Windows.Forms.Label();
            this.txtRegName = new System.Windows.Forms.TextBox();
            this.lblRegEmail = new System.Windows.Forms.Label();
            this.txtRegEmail = new System.Windows.Forms.TextBox();
            this.lblRegEmailError = new System.Windows.Forms.Label();
            this.lblRegPassword = new System.Windows.Forms.Label();
            this.txtRegPassword = new System.Windows.Forms.TextBox();
            this.btnShowRegPassword = new FontAwesome.Sharp.IconButton();
            this.lblRegPasswordStrength = new System.Windows.Forms.Label();
            this.lblRegPasswordConfirm = new System.Windows.Forms.Label();
            this.txtRegPasswordConfirm = new System.Windows.Forms.TextBox();
            this.btnShowRegPasswordConfirm = new FontAwesome.Sharp.IconButton();
            this.lblRegPasswordConfirmError = new System.Windows.Forms.Label();
            this.lblRegisterError = new System.Windows.Forms.Label();
            this.btnRegister = new System.Windows.Forms.Button();
            this.btnGoToLogin = new FontAwesome.Sharp.IconButton();
            this.pnlSidebar.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.iconBook)).BeginInit();
            this.pnlRight.SuspendLayout();
            this.pnlLogin.SuspendLayout();
            this.pnlRegister.SuspendLayout();
            this.SuspendLayout();
            // 
            // txtLoginPassword
            // 
            this.txtLoginPassword.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtLoginPassword.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtLoginPassword.Location = new System.Drawing.Point(22, 179);
            this.txtLoginPassword.Margin = new System.Windows.Forms.Padding(2);
            this.txtLoginPassword.Name = "txtLoginPassword";
            this.txtLoginPassword.Size = new System.Drawing.Size(197, 25);
            this.txtLoginPassword.TabIndex = 1;
            this.txtLoginPassword.UseSystemPasswordChar = true;
            this.txtLoginPassword.TextChanged += new System.EventHandler(this.txtLoginPassword_TextChanged);
            // 
            // lblLoginPassword
            // 
            this.lblLoginPassword.AutoSize = true;
            this.lblLoginPassword.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblLoginPassword.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(60)))), ((int)(((byte)(80)))));
            this.lblLoginPassword.Location = new System.Drawing.Point(22, 158);
            this.lblLoginPassword.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblLoginPassword.Name = "lblLoginPassword";
            this.lblLoginPassword.Size = new System.Drawing.Size(59, 15);
            this.lblLoginPassword.TabIndex = 4;
            this.lblLoginPassword.Text = "Password";
            // 
            // pnlSidebar
            // 
            this.pnlSidebar.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(43)))), ((int)(((byte)(75)))));
            this.pnlSidebar.Controls.Add(this.iconBook);
            this.pnlSidebar.Controls.Add(this.lblAppName);
            this.pnlSidebar.Controls.Add(this.lblAppSubtitle);
            this.pnlSidebar.Dock = System.Windows.Forms.DockStyle.Left;
            this.pnlSidebar.Location = new System.Drawing.Point(0, 0);
            this.pnlSidebar.Margin = new System.Windows.Forms.Padding(2);
            this.pnlSidebar.Name = "pnlSidebar";
            this.pnlSidebar.Size = new System.Drawing.Size(172, 536);
            this.pnlSidebar.TabIndex = 1;
            // 
            // iconBook
            // 
            this.iconBook.BackColor = System.Drawing.Color.Transparent;
            this.iconBook.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(179)))), ((int)(((byte)(255)))));
            this.iconBook.IconChar = FontAwesome.Sharp.IconChar.BookOpen;
            this.iconBook.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(179)))), ((int)(((byte)(255)))));
            this.iconBook.IconFont = FontAwesome.Sharp.IconFont.Auto;
            this.iconBook.IconSize = 65;
            this.iconBook.Location = new System.Drawing.Point(0, 89);
            this.iconBook.Margin = new System.Windows.Forms.Padding(2);
            this.iconBook.Name = "iconBook";
            this.iconBook.Size = new System.Drawing.Size(172, 65);
            this.iconBook.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
            this.iconBook.TabIndex = 0;
            this.iconBook.TabStop = false;
            // 
            // lblAppName
            // 
            this.lblAppName.Font = new System.Drawing.Font("Segoe UI", 16F, System.Drawing.FontStyle.Bold);
            this.lblAppName.ForeColor = System.Drawing.Color.White;
            this.lblAppName.Location = new System.Drawing.Point(8, 162);
            this.lblAppName.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblAppName.Name = "lblAppName";
            this.lblAppName.Size = new System.Drawing.Size(158, 32);
            this.lblAppName.TabIndex = 1;
            this.lblAppName.Text = "Library System";
            this.lblAppName.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // lblAppSubtitle
            // 
            this.lblAppSubtitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblAppSubtitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(160)))), ((int)(((byte)(190)))), ((int)(((byte)(220)))));
            this.lblAppSubtitle.Location = new System.Drawing.Point(11, 199);
            this.lblAppSubtitle.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblAppSubtitle.Name = "lblAppSubtitle";
            this.lblAppSubtitle.Size = new System.Drawing.Size(150, 41);
            this.lblAppSubtitle.TabIndex = 2;
            this.lblAppSubtitle.Text = "Manage your library\r\nefficiently & securely";
            this.lblAppSubtitle.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // pnlRight
            // 
            this.pnlRight.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(250)))));
            this.pnlRight.Controls.Add(this.pnlLogin);
            this.pnlRight.Controls.Add(this.pnlRegister);
            this.pnlRight.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlRight.Location = new System.Drawing.Point(172, 0);
            this.pnlRight.Margin = new System.Windows.Forms.Padding(2);
            this.pnlRight.Name = "pnlRight";
            this.pnlRight.Size = new System.Drawing.Size(328, 536);
            this.pnlRight.TabIndex = 0;
            // 
            // pnlLogin
            // 
            this.pnlLogin.BackColor = System.Drawing.Color.White;
            this.pnlLogin.Controls.Add(this.lblLoginTitle);
            this.pnlLogin.Controls.Add(this.lblLoginSubtitle);
            this.pnlLogin.Controls.Add(this.lblLoginEmail);
            this.pnlLogin.Controls.Add(this.txtLoginEmail);
            this.pnlLogin.Controls.Add(this.lblLoginEmailError);
            this.pnlLogin.Controls.Add(this.lblLoginPassword);
            this.pnlLogin.Controls.Add(this.txtLoginPassword);
            this.pnlLogin.Controls.Add(this.btnShowLoginPassword);
            this.pnlLogin.Controls.Add(this.lblLoginError);
            this.pnlLogin.Controls.Add(this.btnLogin);
            this.pnlLogin.Controls.Add(this.btnGoToRegister);
            this.pnlLogin.Location = new System.Drawing.Point(22, 20);
            this.pnlLogin.Margin = new System.Windows.Forms.Padding(2);
            this.pnlLogin.Name = "pnlLogin";
            this.pnlLogin.Padding = new System.Windows.Forms.Padding(21, 20, 21, 20);
            this.pnlLogin.Size = new System.Drawing.Size(270, 406);
            this.pnlLogin.TabIndex = 0;
            this.pnlLogin.Paint += new System.Windows.Forms.PaintEventHandler(this.CardPanel_Paint);
            // 
            // lblLoginTitle
            // 
            this.lblLoginTitle.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.lblLoginTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(43)))), ((int)(((byte)(75)))));
            this.lblLoginTitle.Location = new System.Drawing.Point(22, 24);
            this.lblLoginTitle.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblLoginTitle.Name = "lblLoginTitle";
            this.lblLoginTitle.Size = new System.Drawing.Size(225, 32);
            this.lblLoginTitle.TabIndex = 0;
            this.lblLoginTitle.Text = "Welcome Back";
            // 
            // lblLoginSubtitle
            // 
            this.lblLoginSubtitle.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            this.lblLoginSubtitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(130)))), ((int)(((byte)(145)))));
            this.lblLoginSubtitle.Location = new System.Drawing.Point(22, 57);
            this.lblLoginSubtitle.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblLoginSubtitle.Name = "lblLoginSubtitle";
            this.lblLoginSubtitle.Size = new System.Drawing.Size(225, 18);
            this.lblLoginSubtitle.TabIndex = 1;
            this.lblLoginSubtitle.Text = "Sign in to your account to continue";
            // 
            // lblLoginEmail
            // 
            this.lblLoginEmail.AutoSize = true;
            this.lblLoginEmail.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.lblLoginEmail.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(60)))), ((int)(((byte)(80)))));
            this.lblLoginEmail.Location = new System.Drawing.Point(22, 98);
            this.lblLoginEmail.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblLoginEmail.Name = "lblLoginEmail";
            this.lblLoginEmail.Size = new System.Drawing.Size(83, 15);
            this.lblLoginEmail.TabIndex = 2;
            this.lblLoginEmail.Text = "Email Address";
            // 
            // txtLoginEmail
            // 
            this.txtLoginEmail.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtLoginEmail.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtLoginEmail.Location = new System.Drawing.Point(22, 118);
            this.txtLoginEmail.Margin = new System.Windows.Forms.Padding(2);
            this.txtLoginEmail.Name = "txtLoginEmail";
            this.txtLoginEmail.Size = new System.Drawing.Size(226, 25);
            this.txtLoginEmail.TabIndex = 0;
            this.txtLoginEmail.TextChanged += new System.EventHandler(this.txtLoginEmail_TextChanged);
            this.txtLoginEmail.Leave += new System.EventHandler(this.txtLoginEmail_Leave);
            // 
            // lblLoginEmailError
            // 
            this.lblLoginEmailError.AutoSize = true;
            this.lblLoginEmailError.Font = new System.Drawing.Font("Segoe UI", 8F);
            this.lblLoginEmailError.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.lblLoginEmailError.Location = new System.Drawing.Point(22, 142);
            this.lblLoginEmailError.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblLoginEmailError.Name = "lblLoginEmailError";
            this.lblLoginEmailError.Size = new System.Drawing.Size(0, 13);
            this.lblLoginEmailError.TabIndex = 3;
            this.lblLoginEmailError.Visible = false;
            // 
            // btnShowLoginPassword
            // 
            this.btnShowLoginPassword.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(243)))), ((int)(((byte)(248)))));
            this.btnShowLoginPassword.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnShowLoginPassword.FlatAppearance.BorderSize = 0;
            this.btnShowLoginPassword.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(235)))), ((int)(((byte)(245)))));
            this.btnShowLoginPassword.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnShowLoginPassword.IconChar = FontAwesome.Sharp.IconChar.Eye;
            this.btnShowLoginPassword.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(130)))), ((int)(((byte)(145)))));
            this.btnShowLoginPassword.IconFont = FontAwesome.Sharp.IconFont.Auto;
            this.btnShowLoginPassword.IconSize = 20;
            this.btnShowLoginPassword.Location = new System.Drawing.Point(222, 178);
            this.btnShowLoginPassword.Margin = new System.Windows.Forms.Padding(2);
            this.btnShowLoginPassword.Name = "btnShowLoginPassword";
            this.btnShowLoginPassword.Size = new System.Drawing.Size(26, 26);
            this.btnShowLoginPassword.TabIndex = 2;
            this.btnShowLoginPassword.UseVisualStyleBackColor = false;
            this.btnShowLoginPassword.Click += new System.EventHandler(this.btnShowLoginPassword_Click);
            // 
            // lblLoginError
            // 
            this.lblLoginError.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(235)))), ((int)(((byte)(235)))));
            this.lblLoginError.Font = new System.Drawing.Font("Segoe UI", 8.5F);
            this.lblLoginError.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.lblLoginError.Location = new System.Drawing.Point(22, 207);
            this.lblLoginError.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblLoginError.Name = "lblLoginError";
            this.lblLoginError.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblLoginError.Size = new System.Drawing.Size(225, 37);
            this.lblLoginError.TabIndex = 5;
            this.lblLoginError.Visible = false;
            // 
            // btnLogin
            // 
            this.btnLogin.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(99)))), ((int)(((byte)(235)))));
            this.btnLogin.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnLogin.FlatAppearance.BorderSize = 0;
            this.btnLogin.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnLogin.Font = new System.Drawing.Font("Segoe UI", 10.5F, System.Drawing.FontStyle.Bold);
            this.btnLogin.ForeColor = System.Drawing.Color.White;
            this.btnLogin.Location = new System.Drawing.Point(22, 260);
            this.btnLogin.Margin = new System.Windows.Forms.Padding(2);
            this.btnLogin.Name = "btnLogin";
            this.btnLogin.Size = new System.Drawing.Size(225, 34);
            this.btnLogin.TabIndex = 3;
            this.btnLogin.Text = "Sign In";
            this.btnLogin.UseVisualStyleBackColor = false;
            this.btnLogin.Click += new System.EventHandler(this.btnLogin_Click);
            // 
            // btnGoToRegister
            // 
            this.btnGoToRegister.BackColor = System.Drawing.Color.Transparent;
            this.btnGoToRegister.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnGoToRegister.FlatAppearance.BorderSize = 0;
            this.btnGoToRegister.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnGoToRegister.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnGoToRegister.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(99)))), ((int)(((byte)(235)))));
            this.btnGoToRegister.IconChar = FontAwesome.Sharp.IconChar.ArrowRight;
            this.btnGoToRegister.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(99)))), ((int)(((byte)(235)))));
            this.btnGoToRegister.IconFont = FontAwesome.Sharp.IconFont.Auto;
            this.btnGoToRegister.IconSize = 16;
            this.btnGoToRegister.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGoToRegister.Location = new System.Drawing.Point(22, 305);
            this.btnGoToRegister.Margin = new System.Windows.Forms.Padding(2);
            this.btnGoToRegister.Name = "btnGoToRegister";
            this.btnGoToRegister.Size = new System.Drawing.Size(225, 31);
            this.btnGoToRegister.TabIndex = 4;
            this.btnGoToRegister.Text = "Don\'t have an account?  Register   ";
            this.btnGoToRegister.TextImageRelation = System.Windows.Forms.TextImageRelation.TextBeforeImage;
            this.btnGoToRegister.UseVisualStyleBackColor = false;
            this.btnGoToRegister.Click += new System.EventHandler(this.btnGoToRegister_Click);
            // 
            // pnlRegister
            // 
            this.pnlRegister.BackColor = System.Drawing.Color.White;
            this.pnlRegister.Controls.Add(this.lblRegTitle);
            this.pnlRegister.Controls.Add(this.lblRegSubtitle);
            this.pnlRegister.Controls.Add(this.lblRegName);
            this.pnlRegister.Controls.Add(this.txtRegName);
            this.pnlRegister.Controls.Add(this.lblRegEmail);
            this.pnlRegister.Controls.Add(this.txtRegEmail);
            this.pnlRegister.Controls.Add(this.lblRegEmailError);
            this.pnlRegister.Controls.Add(this.lblRegPassword);
            this.pnlRegister.Controls.Add(this.txtRegPassword);
            this.pnlRegister.Controls.Add(this.btnShowRegPassword);
            this.pnlRegister.Controls.Add(this.lblRegPasswordStrength);
            this.pnlRegister.Controls.Add(this.lblRegPasswordConfirm);
            this.pnlRegister.Controls.Add(this.txtRegPasswordConfirm);
            this.pnlRegister.Controls.Add(this.btnShowRegPasswordConfirm);
            this.pnlRegister.Controls.Add(this.lblRegPasswordConfirmError);
            this.pnlRegister.Controls.Add(this.lblRegisterError);
            this.pnlRegister.Controls.Add(this.btnRegister);
            this.pnlRegister.Controls.Add(this.btnGoToLogin);
            this.pnlRegister.Location = new System.Drawing.Point(22, 20);
            this.pnlRegister.Margin = new System.Windows.Forms.Padding(2);
            this.pnlRegister.Name = "pnlRegister";
            this.pnlRegister.Padding = new System.Windows.Forms.Padding(21, 20, 21, 20);
            this.pnlRegister.Size = new System.Drawing.Size(270, 406);
            this.pnlRegister.TabIndex = 1;
            this.pnlRegister.Visible = false;
            this.pnlRegister.Paint += new System.Windows.Forms.PaintEventHandler(this.CardPanel_Paint);
            // 
            // lblRegTitle
            // 
            this.lblRegTitle.Font = new System.Drawing.Font("Segoe UI", 16F, System.Drawing.FontStyle.Bold);
            this.lblRegTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(43)))), ((int)(((byte)(75)))));
            this.lblRegTitle.Location = new System.Drawing.Point(22, 12);
            this.lblRegTitle.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblRegTitle.Name = "lblRegTitle";
            this.lblRegTitle.Size = new System.Drawing.Size(225, 28);
            this.lblRegTitle.TabIndex = 0;
            this.lblRegTitle.Text = "Create Account";
            // 
            // lblRegSubtitle
            // 
            this.lblRegSubtitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblRegSubtitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(130)))), ((int)(((byte)(145)))));
            this.lblRegSubtitle.Location = new System.Drawing.Point(22, 41);
            this.lblRegSubtitle.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblRegSubtitle.Name = "lblRegSubtitle";
            this.lblRegSubtitle.Size = new System.Drawing.Size(225, 16);
            this.lblRegSubtitle.TabIndex = 1;
            this.lblRegSubtitle.Text = "Fill in the details to register";
            // 
            // lblRegName
            // 
            this.lblRegName.AutoSize = true;
            this.lblRegName.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.lblRegName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(60)))), ((int)(((byte)(80)))));
            this.lblRegName.Location = new System.Drawing.Point(22, 65);
            this.lblRegName.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblRegName.Name = "lblRegName";
            this.lblRegName.Size = new System.Drawing.Size(62, 15);
            this.lblRegName.TabIndex = 2;
            this.lblRegName.Text = "Full Name";
            // 
            // txtRegName
            // 
            this.txtRegName.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtRegName.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtRegName.Location = new System.Drawing.Point(22, 83);
            this.txtRegName.Margin = new System.Windows.Forms.Padding(2);
            this.txtRegName.Name = "txtRegName";
            this.txtRegName.Size = new System.Drawing.Size(226, 25);
            this.txtRegName.TabIndex = 0;
            this.txtRegName.TextChanged += new System.EventHandler(this.txtRegName_TextChanged);
            // 
            // lblRegEmail
            // 
            this.lblRegEmail.AutoSize = true;
            this.lblRegEmail.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.lblRegEmail.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(60)))), ((int)(((byte)(80)))));
            this.lblRegEmail.Location = new System.Drawing.Point(22, 115);
            this.lblRegEmail.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblRegEmail.Name = "lblRegEmail";
            this.lblRegEmail.Size = new System.Drawing.Size(83, 15);
            this.lblRegEmail.TabIndex = 3;
            this.lblRegEmail.Text = "Email Address";
            // 
            // txtRegEmail
            // 
            this.txtRegEmail.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtRegEmail.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtRegEmail.Location = new System.Drawing.Point(22, 133);
            this.txtRegEmail.Margin = new System.Windows.Forms.Padding(2);
            this.txtRegEmail.Name = "txtRegEmail";
            this.txtRegEmail.Size = new System.Drawing.Size(226, 25);
            this.txtRegEmail.TabIndex = 1;
            this.txtRegEmail.TextChanged += new System.EventHandler(this.txtRegEmail_TextChanged);
            this.txtRegEmail.Leave += new System.EventHandler(this.txtRegEmail_Leave);
            // 
            // lblRegEmailError
            // 
            this.lblRegEmailError.AutoSize = true;
            this.lblRegEmailError.Font = new System.Drawing.Font("Segoe UI", 8F);
            this.lblRegEmailError.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.lblRegEmailError.Location = new System.Drawing.Point(22, 158);
            this.lblRegEmailError.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblRegEmailError.Name = "lblRegEmailError";
            this.lblRegEmailError.Size = new System.Drawing.Size(0, 13);
            this.lblRegEmailError.TabIndex = 4;
            this.lblRegEmailError.Visible = false;
            // 
            // lblRegPassword
            // 
            this.lblRegPassword.AutoSize = true;
            this.lblRegPassword.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.lblRegPassword.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(60)))), ((int)(((byte)(80)))));
            this.lblRegPassword.Location = new System.Drawing.Point(22, 166);
            this.lblRegPassword.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblRegPassword.Name = "lblRegPassword";
            this.lblRegPassword.Size = new System.Drawing.Size(59, 15);
            this.lblRegPassword.TabIndex = 5;
            this.lblRegPassword.Text = "Password";
            // 
            // txtRegPassword
            // 
            this.txtRegPassword.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtRegPassword.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtRegPassword.Location = new System.Drawing.Point(22, 184);
            this.txtRegPassword.Margin = new System.Windows.Forms.Padding(2);
            this.txtRegPassword.Name = "txtRegPassword";
            this.txtRegPassword.UseSystemPasswordChar = true;
            this.txtRegPassword.Size = new System.Drawing.Size(197, 25);
            this.txtRegPassword.TabIndex = 2;
            // 
            // btnShowRegPassword
            // 
            this.btnShowRegPassword.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(243)))), ((int)(((byte)(248)))));
            this.btnShowRegPassword.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnShowRegPassword.FlatAppearance.BorderSize = 0;
            this.btnShowRegPassword.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(235)))), ((int)(((byte)(245)))));
            this.btnShowRegPassword.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnShowRegPassword.IconChar = FontAwesome.Sharp.IconChar.Eye;
            this.btnShowRegPassword.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(130)))), ((int)(((byte)(145)))));
            this.btnShowRegPassword.IconFont = FontAwesome.Sharp.IconFont.Auto;
            this.btnShowRegPassword.IconSize = 20;
            this.btnShowRegPassword.Location = new System.Drawing.Point(222, 183);
            this.btnShowRegPassword.Margin = new System.Windows.Forms.Padding(2);
            this.btnShowRegPassword.Name = "btnShowRegPassword";
            this.btnShowRegPassword.Size = new System.Drawing.Size(26, 24);
            this.btnShowRegPassword.TabIndex = 3;
            this.btnShowRegPassword.UseVisualStyleBackColor = false;
            this.btnShowRegPassword.Click += new System.EventHandler(this.btnShowRegPassword_Click);
            // 
            // lblRegPasswordStrength
            // 
            this.lblRegPasswordStrength.AutoSize = true;
            this.lblRegPasswordStrength.Font = new System.Drawing.Font("Segoe UI", 8F, System.Drawing.FontStyle.Bold);
            this.lblRegPasswordStrength.Location = new System.Drawing.Point(22, 208);
            this.lblRegPasswordStrength.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblRegPasswordStrength.Name = "lblRegPasswordStrength";
            this.lblRegPasswordStrength.Size = new System.Drawing.Size(0, 13);
            this.lblRegPasswordStrength.TabIndex = 6;
            // 
            // lblRegPasswordConfirm
            // 
            this.lblRegPasswordConfirm.AutoSize = true;
            this.lblRegPasswordConfirm.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Bold);
            this.lblRegPasswordConfirm.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(50)))), ((int)(((byte)(60)))), ((int)(((byte)(80)))));
            this.lblRegPasswordConfirm.Location = new System.Drawing.Point(22, 216);
            this.lblRegPasswordConfirm.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblRegPasswordConfirm.Name = "lblRegPasswordConfirm";
            this.lblRegPasswordConfirm.Size = new System.Drawing.Size(107, 15);
            this.lblRegPasswordConfirm.TabIndex = 7;
            this.lblRegPasswordConfirm.Text = "Confirm Password";
            // 
            // txtRegPasswordConfirm
            // 
            this.txtRegPasswordConfirm.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.txtRegPasswordConfirm.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtRegPasswordConfirm.Location = new System.Drawing.Point(22, 234);
            this.txtRegPasswordConfirm.Margin = new System.Windows.Forms.Padding(2);
            this.txtRegPasswordConfirm.Name = "txtRegPasswordConfirm";
            this.txtRegPasswordConfirm.UseSystemPasswordChar = true;
            this.txtRegPasswordConfirm.Size = new System.Drawing.Size(197, 25);
            this.txtRegPasswordConfirm.TabIndex = 3;
            // 
            // btnShowRegPasswordConfirm
            // 
            this.btnShowRegPasswordConfirm.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(243)))), ((int)(((byte)(248)))));
            this.btnShowRegPasswordConfirm.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnShowRegPasswordConfirm.FlatAppearance.BorderSize = 0;
            this.btnShowRegPasswordConfirm.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(235)))), ((int)(((byte)(245)))));
            this.btnShowRegPasswordConfirm.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnShowRegPasswordConfirm.IconChar = FontAwesome.Sharp.IconChar.Eye;
            this.btnShowRegPasswordConfirm.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(120)))), ((int)(((byte)(130)))), ((int)(((byte)(145)))));
            this.btnShowRegPasswordConfirm.IconFont = FontAwesome.Sharp.IconFont.Auto;
            this.btnShowRegPasswordConfirm.IconSize = 20;
            this.btnShowRegPasswordConfirm.Location = new System.Drawing.Point(222, 233);
            this.btnShowRegPasswordConfirm.Margin = new System.Windows.Forms.Padding(2);
            this.btnShowRegPasswordConfirm.Name = "btnShowRegPasswordConfirm";
            this.btnShowRegPasswordConfirm.Size = new System.Drawing.Size(26, 24);
            this.btnShowRegPasswordConfirm.TabIndex = 5;
            this.btnShowRegPasswordConfirm.UseVisualStyleBackColor = false;
            this.btnShowRegPasswordConfirm.Click += new System.EventHandler(this.btnShowRegPasswordConfirm_Click);
            // 
            // lblRegPasswordConfirmError
            // 
            this.lblRegPasswordConfirmError.AutoSize = true;
            this.lblRegPasswordConfirmError.Font = new System.Drawing.Font("Segoe UI", 8F);
            this.lblRegPasswordConfirmError.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(50)))), ((int)(((byte)(50)))));
            this.lblRegPasswordConfirmError.Location = new System.Drawing.Point(22, 258);
            this.lblRegPasswordConfirmError.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblRegPasswordConfirmError.Name = "lblRegPasswordConfirmError";
            this.lblRegPasswordConfirmError.Size = new System.Drawing.Size(0, 13);
            this.lblRegPasswordConfirmError.TabIndex = 8;
            this.lblRegPasswordConfirmError.Visible = false;
            // 
            // lblRegisterError
            // 
            this.lblRegisterError.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(235)))), ((int)(((byte)(235)))));
            this.lblRegisterError.Font = new System.Drawing.Font("Segoe UI", 8.5F);
            this.lblRegisterError.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(180)))), ((int)(((byte)(30)))), ((int)(((byte)(30)))));
            this.lblRegisterError.Location = new System.Drawing.Point(22, 272);
            this.lblRegisterError.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.lblRegisterError.Name = "lblRegisterError";
            this.lblRegisterError.Padding = new System.Windows.Forms.Padding(6, 0, 0, 0);
            this.lblRegisterError.Size = new System.Drawing.Size(225, 37);
            this.lblRegisterError.TabIndex = 9;
            this.lblRegisterError.Visible = false;
            // 
            // btnRegister
            // 
            this.btnRegister.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(99)))), ((int)(((byte)(235)))));
            this.btnRegister.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnRegister.FlatAppearance.BorderSize = 0;
            this.btnRegister.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnRegister.Font = new System.Drawing.Font("Segoe UI", 10.5F, System.Drawing.FontStyle.Bold);
            this.btnRegister.ForeColor = System.Drawing.Color.White;
            this.btnRegister.Location = new System.Drawing.Point(22, 317);
            this.btnRegister.Margin = new System.Windows.Forms.Padding(2);
            this.btnRegister.Name = "btnRegister";
            this.btnRegister.Size = new System.Drawing.Size(225, 34);
            this.btnRegister.TabIndex = 6;
            this.btnRegister.Text = "Create Account";
            this.btnRegister.UseVisualStyleBackColor = false;
            this.btnRegister.Click += new System.EventHandler(this.btnRegister_Click);
            // 
            // btnGoToLogin
            // 
            this.btnGoToLogin.BackColor = System.Drawing.Color.Transparent;
            this.btnGoToLogin.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnGoToLogin.FlatAppearance.BorderSize = 0;
            this.btnGoToLogin.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnGoToLogin.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnGoToLogin.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(99)))), ((int)(((byte)(235)))));
            this.btnGoToLogin.IconChar = FontAwesome.Sharp.IconChar.ArrowRight;
            this.btnGoToLogin.IconColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(99)))), ((int)(((byte)(235)))));
            this.btnGoToLogin.IconFont = FontAwesome.Sharp.IconFont.Auto;
            this.btnGoToLogin.IconSize = 16;
            this.btnGoToLogin.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGoToLogin.Location = new System.Drawing.Point(22, 362);
            this.btnGoToLogin.Margin = new System.Windows.Forms.Padding(2);
            this.btnGoToLogin.Name = "btnGoToLogin";
            this.btnGoToLogin.Size = new System.Drawing.Size(225, 31);
            this.btnGoToLogin.TabIndex = 7;
            this.btnGoToLogin.Text = "Already have an account?  Sign In   ";
            this.btnGoToLogin.TextImageRelation = System.Windows.Forms.TextImageRelation.TextBeforeImage;
            this.btnGoToLogin.UseVisualStyleBackColor = false;
            this.btnGoToLogin.Click += new System.EventHandler(this.btnGoToLogin_Click);
            // 
            // LoginRegisterForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(500, 536);
            this.Controls.Add(this.pnlRight);
            this.Controls.Add(this.pnlSidebar);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "LoginRegisterForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Library System - Authentication";
            this.pnlSidebar.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.iconBook)).EndInit();
            this.pnlRight.ResumeLayout(false);
            this.pnlLogin.ResumeLayout(false);
            this.pnlLogin.PerformLayout();
            this.pnlRegister.ResumeLayout(false);
            this.pnlRegister.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        // Sidebar
        private System.Windows.Forms.Panel pnlSidebar;
        private FontAwesome.Sharp.IconPictureBox iconBook;
        private System.Windows.Forms.Label lblAppName;
        private System.Windows.Forms.Label lblAppSubtitle;
        // Right host
        private System.Windows.Forms.Panel pnlRight;
        // Login card
        private System.Windows.Forms.Panel pnlLogin;
        private System.Windows.Forms.Label lblLoginTitle;
        private System.Windows.Forms.Label lblLoginSubtitle;
        private System.Windows.Forms.Label lblLoginEmail;
        private System.Windows.Forms.TextBox txtLoginEmail;
        private System.Windows.Forms.Label lblLoginEmailError;
        private System.Windows.Forms.Label lblLoginPassword;
        private System.Windows.Forms.TextBox txtLoginPassword;
        private FontAwesome.Sharp.IconButton btnShowLoginPassword;
        private System.Windows.Forms.Label lblLoginError;
        private System.Windows.Forms.Button btnLogin;
        private FontAwesome.Sharp.IconButton btnGoToRegister;
        // Register card
        private System.Windows.Forms.Panel pnlRegister;
        private System.Windows.Forms.Label lblRegTitle;
        private System.Windows.Forms.Label lblRegSubtitle;
        private System.Windows.Forms.Label lblRegName;
        private System.Windows.Forms.TextBox txtRegName;
        private System.Windows.Forms.Label lblRegEmail;
        private System.Windows.Forms.TextBox txtRegEmail;
        private System.Windows.Forms.Label lblRegEmailError;
        private System.Windows.Forms.Label lblRegPassword;
        private System.Windows.Forms.TextBox txtRegPassword;
        private FontAwesome.Sharp.IconButton btnShowRegPassword;
        private System.Windows.Forms.Label lblRegPasswordStrength;
        private System.Windows.Forms.Label lblRegPasswordConfirm;
        private System.Windows.Forms.TextBox txtRegPasswordConfirm;
        private FontAwesome.Sharp.IconButton btnShowRegPasswordConfirm;
        private System.Windows.Forms.Label lblRegPasswordConfirmError;
        private System.Windows.Forms.Label lblRegisterError;
        private System.Windows.Forms.Button btnRegister;
        private FontAwesome.Sharp.IconButton btnGoToLogin;
    }
}










